---
- name: Gather OS Specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- name: Install munin-node packages
  package:
    name: "{{ munin_node_pkg }}"
    state: present
  tags: install

- name: Config munin-node
  template:
    src: munin-node.conf.j2
    dest: "{{ munin_node_conf }}"
    mode: '0644'
  notify: restart munin-node
  tags: config

- name: Start / enable service munin-node
  systemd:
    name: munin-node
    state: started
    enabled: yes
  tags: setup
